$ModelName "andy/cats/cat_singer.mdl"
$Scale 0.9
$Body "cat_singer" "cat_singer.dmx"

$SurfaceProp "default"
$opaque
$Contents "solid"

$CDMaterials "models\andy\singer"

$TextureGroup "skinfamilies"
{
	{ "cat_singer_01" }
	{ "cat_singer_02" }
	{ "cat_singer_03" }
	{ "cat_singer_04" }
	{ "cat_singer_05" }
	{ "cat_singer_06" }
	{ "cat_singer_07" }
	{ "cat_singer_08" }
	{ "cat_singer_09" }
}

$include "sequences.qci"
