$ModelName "andy/cats/cat_pianist.mdl"
$Scale 1.1
$Body "cat_pianist" "cat_pianist.dmx"

$SurfaceProp "default"
$opaque
$Contents "solid"

$CDMaterials "models\andy\pianist"

$TextureGroup "skinfamilies"
{
	{ "cat_pianist_01" }
	{ "cat_pianist_02" }
	{ "cat_pianist_03" }
	{ "cat_pianist_04" }
	{ "cat_pianist_05" }
	{ "cat_pianist_06" }
	{ "cat_pianist_07" }
}

//$illumposition 0 -1 0

$include "sequences.qci"
